f = open("24.txt")
B = []
for i in f.readlines():
	for s in range(len(i)-2):
		if (i[s] == i[s+2]):
			B.append(i[s+1])
print(B.count('A'),'A')
print(B.count('B'),'B')
print(B.count('C'),'C')
print(B.count('D'),'D')
print(B.count('E'),'E')
print(B.count('F'),'F')
print(B.count('G'),'G')
print(B.count('H'),'H')
print(B.count('I'),'I')
print(B.count('J'),'J')
print(B.count('K'),'K')
print(B.count('L'),'L')
print(B.count('M'),'M')
print(B.count('N'),'N')
print(B.count('O'),'O')
print(B.count('P'),'P')
print(B.count('Q'),'Q')
print(B.count('R'),'R')
print(B.count('S'),'S')
print(B.count('T'),'T')
print(B.count('U'),'U')
print(B.count('V'),'V')
print(B.count('W'),'W')
print(B.count('X'),'X')
print(B.count('Y'),'Y')
print(B.count('Z'),'Z')